### ISSUE TITLE
Reduce duplicate versions of math hints

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/cairo-vm#1048]
Some functions have multiple versions, each one only using a different `UintNNN` wrapper to interact with the VM memory. An example are the `u384_get_square_root` and `u256_get_square_root` functions.

This could be solved by extracting the common interface into a trait, and using generics to write these hints only one time.

An alternative would be to make a generic `UintNNN` struct, but that way we wouldn't be able to add custom "member X doesn't exist" for each variant.

Another alternative would be to add all of these variants into an enum.

**Comment by Oppen** [comment]
> An alternative would be to make a generic UintNNN struct, but that way we wouldn't be able to add custom "member X doesn't exist" for each variant.

I think this is actually possible with a little bit of magic.
