### ISSUE TITLE
Remove our Cairo1HintProcessor implementation and use cairo implementation

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo-vm#1216]
see https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-runner/src/casm_run/mod.rs#L1307

**Comment by fmoletta** [comment]
This is currently not possible due to conflicting versions of cairo-rs structs used by the `execute_core_hint_base` function.
An attempt to do so can be found here #1273

**Comment by pefontana** [comment]
Not posibble
