### ISSUE TITLE
Add Fuzzer to the CI

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo-vm#1224]
* Update the fuzzer to the lasted version of cairo-rs 
https://github.com/lambdaclass/fuzzing_examples/tree/main/cairo_fuzz

* We should run the fuzzer in the CI

to talk:
* When we should run the fuzzer in the CI (every PR, once a day?)
* Move the fuzzer to cairo-rs repo

**Comment by MegaRedHand** [comment]
Merged at 1932562465da7177810829d29e5d677ed2587440
