### ISSUE TITLE
make-deps commands should intall pyenv

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo-vm#1242]
Make deps and Make deps-macos should install pyenv.

**Comment by Oppen** [comment]
The process is highly dependent on the users' platform, so there's no generic way to install this in the target. Instead, the need should be properly documented, with the procedure for some common platforms (off the top of my head, MacOS, Windows, Ubuntu, Debian, CentOS/Red Hat, as those are the most popular ones) explained as well, and if at all possible `make deps` should fail with a clear message and point to the docs if it can't find `pyenv`.
We have a pipeline that checks all of this is installable IIRC, so the commands can be found there.

**Comment by MegaRedHand** [comment]
Addressed in #1298
