### ISSUE TITLE
hint_processors_utils symbols could be public

### ISSUE THREAD

**Issue by tdelabro** [lambdaclass/cairo-vm#1259]
`cairo-rs/vm/src/hint_processor/cairo_1_hint_processor/hint_processor_utils.rs` contains a bunch of func which have been duplicated in [starkwarelibs/cairo](https://github.com/starkware-libs/cairo/blob/05d4a9ec46885ac199025f829c9458989c1ddbba/crates/cairo-lang-runner/src/casm_run/mod.rs#L96)

Those symbols could be public rather than pub(crate) in order to reduce code duplication between the two repositories. And any other repository that want to implement the HintProcessor trait

**Comment by Oppen** [comment]
@juanbono @pefontana do you know if this is specific to the Cairo-1 hint processor or something we'll need to keep? Just to know if we can simply wait for the removal of our downstream copy. Related: #1216
