### ISSUE TITLE
Benchmark the cairo-vm vs revm

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo-vm#1303]
https://github.com/bluealloy/revm

This issue does not require merging any PR.
But we need to compare the execution time of a Fibonacci run between the cairo-vm vs revm.
Aldo it will be good to make the compartion with hyperfine, we can do it with a `time` in the terminal

The Fibonacci algorithm should have the same implementation as the one done here
https://github.com/lambdaclass/cairo-vm/tree/fib-benchmarks

**Comment by pefontana** [comment]
note: use lambdaworks in cairo-vm

**Comment by Oppen** [comment]
For context, how do we use revm? Is that a Cairo VM or does it execute some other language?

**Comment by pefontana** [comment]
that's the hard part of the issue hahah
using the Rust Ethereum virtual machine and coding in solidity
