### ISSUE TITLE
Position Independent Execution

### ISSUE THREAD

**Issue by drspacemn** [lambdaclass/cairo-vm#1305]
**Describe the solution you'd like**
Subsequent to the execution of the CairoRunner allow for the extraction of the Position Independent Execution representation.

[Python Reference](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/lang/vm/cairo_pie.py)

Related description
```
A CairoPie is a serializable object containing information about a run of a cairo program.
Using the information, one can 'relocate' segments of the run, to make another valid cairo run. 
For example, this may be used to join a few cairo runs into one, by concatenating respective 
segments.
```

**Comment by fmoletta** [comment]
Addressed by #1375
