### ISSUE TITLE
Refactor: combine `Program.hints` and `Program.hints_ranges` into a custom collection

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/cairo-vm#1342]
Currently, the `Program` struct contains two fields `hints` and `hints_ranges`, where the second one is used to index the first.

https://github.com/lambdaclass/cairo-vm/blob/7e5378a8fd0c44718fcab523273334b7f75a27dc/vm/src/types/program.rs#L51-L53

As they are strongly related two each other, they should be combined into a single collection that encapsulates the creation and indexing of hints. Some related functionality would be:
- `Program::flatten_hints` (a kind of constructor for it),

https://github.com/lambdaclass/cairo-vm/blob/7e5378a8fd0c44718fcab523273334b7f75a27dc/vm/src/types/program.rs#L121-L124

- and indexing operations (they are used in more than one place)

https://github.com/lambdaclass/cairo-vm/blob/7e5378a8fd0c44718fcab523273334b7f75a27dc/vm/src/vm/runners/cairo_runner.rs#L589-L595

**Comment by PanGan21** [comment]
Hi! I did some effort to achieve this refactor in the pr mentioned above. Let me know if it would require more changes :)
