### ISSUE TITLE
 Different behaviour between vms

### ISSUE THREAD

**Issue by daphneherlambda** [lambdaclass/cairo-vm#1376]
# Different behaviour between vms
Running a cairo compiled program doesn´t return any error while running in the original python implementation of the vm returns an IdentifierError.

# To Reproduce

1. Compile the following .cairo program
```
from starkware.cairo.common.cairo_secp.bigint import BigInt3
struct MyStruct0 {
	low: felt,
	high: felt,
}
func main() {
	let a = BigInt3(d0=1, d1=1, d2=1);
	let b = BigInt3(d0=1, d1=1, d2=1);
	hint_func(a, b);
	return();
}

func hint_func(a: BigInt3, b: BigInt3) -> (BigInt3, BigInt3, MyStruct0) {
	alloc_locals;
	local res: MyStruct0;
%{
def split(num: int, num_bits_shift: int = 128, length: int = 2):
    a = []
    for _ in range(length):
        a.append( num & ((1 << num_bits_shift) - 1) )
        num = num >> num_bits_shift
    return tuple(a)

def pack(z, num_bits_shift: int = 128) -> int:
    limbs = (z.low, z.high)
    return sum(limb << (num_bits_shift * i) for i, limb in enumerate(limbs))

a = pack(ids.a)
b = pack(ids.b)
res = (a - b)%2**256
res_split = split(res)
ids.res.low = res_split[0]
ids.res.high = res_split[1]
%}
	return(a, b, res);
}

```
2. Run the program with the original python implementation using the command cairo-run --program 0x0.json  
3. Run the program with the current implementation using the command /target/release/cairo-vm-cli 0x0.json
See the difference between the results
# Expected behavior
Both implementations should return the same result, in this case, the IdentifierError

# What version/commit are you on?
v0.8.5

**Comment by Oppen** [comment]
Do we have a traceback for this? Which identifier should be failing?
