### ISSUE TITLE
feat: CairoPieMemory Serialization

### ISSUE THREAD

**Issue by drspacemn** [lambdaclass/cairo-vm#1446]
Serialization of the CairoPieMemory trace needs to be handled as in the python VM here:
- https://github.com/starkware-libs/cairo-lang/blob/27a157d761ae49b242026bcbe5fca6e60c1e98bd/src/starkware/cairo/lang/vm/memory_dict.py#L218

Byte serialization defined here:
- https://github.com/starkware-libs/cairo-lang/blob/27a157d761ae49b242026bcbe5fca6e60c1e98bd/src/starkware/cairo/lang/vm/relocatable.py#L74

Implementation options available here:
- https://github.com/keep-starknet-strange/snos/blob/3c37b442e06069bf304ad19eae917170139c2330/src/pie.rs#L42

**Comment by pefontana** [comment]
Done #1447 ##1444 #1438
