### ISSUE TITLE
Passing Struct Arguments to CairoRun

### ISSUE THREAD

**Issue by raphaelDkhn** [lambdaclass/cairo-vm#1506]
I'm working with CairoVM to execute Cairo programs including arguments. However, I'm facing challenges when these arguments are complex data structures.

The program I aim to run using CairoVM is as follows:
```rust
struct Tensor<T> {
    shape: Span<usize>,
    data: Span<T>,
}

fn predict(x: Tensor<u32>) -> Tensor<u32> {
    // ... (program logic here)
}
```

The challenge arises with the argument, which is a struct in this case. I'm struggling to properly construct this struct argument to pass it to `cairo_runner.run_from_entrypoint`.

As a temporary workaround, I thought to serialize the struct and passing the array of felt into the function instead. However, I'm seeking a more efficient or appropriate method for handling this. Any suggestions or guidance would be greatly appreciated.

**Comment by pefontana** [comment]
Hi @raphaelDkhn !
Can you leave here the .cairo program and the code where you are executing the **cairo_runner.run_from_entrypoint**, so we can replicate it?

**Comment by raphaelDkhn** [comment]
Hi @pefontana !

[Here](https://github.com/raphaelDkhn/orion_runner/blob/1864d32b6dfae19f219a586d75c1c53cc706179e/example/src/lib.cairo#L12) you have the cairo program. 

It takes a Tensor struct (from [Orion](https://github.com/gizatechxyz/orion) lib) as argument. 
I'm not sure how to pass the struct in call data when I call `run_from_entrypoint` function [here](https://github.com/raphaelDkhn/orion_runner/blob/1864d32b6dfae19f219a586d75c1c53cc706179e/src/main.rs#L22).

Thank you!

**Comment by pefontana** [comment]
Great @raphaelDkhn !
So, we can help you with something more?

**Comment by raphaelDkhn** [comment]
I think, all good! We can close the issue. Thank you!

**Comment by pefontana** [comment]
Thank you @raphaelDkhn !!
Any other issue you encounter please ask us, happy to help
