### ISSUE TITLE
Implement Air Private Inputs

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo-vm#1526]
In the Cairo1-run crate we should implement the option to return the Air Private Inputs.
To implement this we should see how they are implemented in the Python VM

https://github.com/starkware-libs/cairo-lang/blob/caba294d82eeeccc3d86a158adb8ba209bf2d8fc/src/starkware/cairo/lang/vm/cairo_run.py#L430-L431

Here is and example on how to execute them
`cairo-run --program cairo_programs/proof_programs/_keccak.json --layout starknet_with_keccak --air_public_input=_keccak_public_input.json   --air_private_input=_keccak_private_input.json   --trace_file=_keccak_trace.json   --memory_file=_keccak_memory.json   --print_output   --proof_mode`

**Comment by MauroToscano** [comment]
As a side note, this would be useful for cairo 0 too, and maybe easier to test with that one first
