### ISSUE TITLE
Error in Cairo Program Execution: NoBuiltinForInstance Issue in PR #1551

### ISSUE THREAD

**Issue by raphaelDkhn** [lambdaclass/cairo-vm#1558]
**Describe the bug**
Hi @fmoletta, I've encountered an issue related to your PR #1551. When executing the following command in cairo1-run:
`cargo run ../cairo_programs/cairo-1-programs/array_input_sum.cairo --args '2 [1 2 3 4] 0 [9 8]'`
I encounter an error message:
```
Error: Runner(NoBuiltinForInstance(({"range_check_builtin"}, "plain")))
```

This error is probably causing by `*array.at(...)` in the cairo program.

**What version/commit are you on?**
Current Version/Commit: Branch `cairo-1-input-args`

**Comment by fmoletta** [comment]
Hello! It looks like the command is missing the `--layout` flag. Without specifying the layout the default one is `plain`, which doesn't have any builtins, adding `--layout all_cairo` should fix it. Thanks for the catch, I'll update the README example.
