### ISSUE TITLE
Update Cairo 2 compiler to 2.5.3 

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo-vm#1621]
Update the compiler version for Cairo 2 programs to v2.5.3 
https://github.com/lambdaclass/cairo-vm/blob/main/Makefile#L171

This bump will imply some changes in some Cairo programs

**Comment by Joy-Adah** [comment]
can i do this?

**Comment by fmoletta** [comment]
Already bumped to 2.5.4
