### ISSUE TITLE
Refactor cairo1-run crate for library use

### ISSUE THREAD

**Issue by barabanovro** [lambdaclass/cairo-vm#1623]
**Is your feature request related to a problem? Please describe.**
The current implementation of `cairo1-run` crate as a CLI restricts its usability in other projects that could benefit from its functionality as a library.

**Describe the solution you'd like**
Transform the `cairo1-run` crate into a standalone library that can be used by external projects. Ideally, the `run` function would return:

1. Output of program execution.
2. Relocated trace and memory.
3. Sierra (with debug info) and CASM programs.
4. CASM additional instructions (proof_mode_header, entry_code, libfunc_footer).
5. Diagnostics.
6. Compiler RootDatabase.

**Motivation**
We need it for https://cairovm.codes and https://walnut.dev — projects aiming to build a debugger for Cairo / Starknet.

**Comment by fmoletta** [comment]
Hello! We recently refactored the `cairo1-run` crate to also expose  a `cairo_run_program` function that takes a sierra program and returns the runner, vm, and return values after the run #1601

**Comment by fmoletta** [comment]
Closed by #1714
