### ISSUE TITLE
Feature request: Enable Loading Arguments from File Path to Overcome Shell Argument Length Limitations

### ISSUE THREAD

**Issue by Okm165** [lambdaclass/cairo-vm#1728]
**Problem Description:**
Currently, the `cairo1-run` tool can only receive arguments to the Cairo program entry code via shell arguments. This setup imposes limitations on passing large data due to restrictions on the length of shell arguments. This limitation became evident when attempting to supply zkproof serialized to `Vec<Felt252>`, resulting in shell errors due to the number of arguments being too large.

**Proposed Solution:**
To overcome this limitation, the suggestion is to enable loading arguments directly from a file path. By doing so, the restriction imposed by the shell on argument length would be bypassed, and the only limitation would be the `i16` offset size.

**Additional Context:**
This feature request is especially relevant given the forthcoming use cases of L3 and zkML, which are expected to involve large data sets. Preparing for such scenarios by addressing limitations in argument passing would be beneficial.

**Comment by Okm165** [comment]
My current understanding is that i16 will limit the number of possible data input to the ca1ro entrypoint is that right?
Is there any way increasing it? The memory segments for arrays won't help afaik coz they still increase i16 offset by num of elements inside.

**Comment by pefontana** [comment]
Hi @Okm165 !
Thanks for the issue. We will work on a way to pass inputs with a file
Do you need more than 32768 inputs?
