### ISSUE TITLE
Add tests for cairo 1 programs returning `Felt252Dict`

### ISSUE THREAD

**Issue by fmoletta** [lambdaclass/cairo-vm#1731]
PR #1721 modified the test programs that returned `Felt252Dict` so that they now return their squashed version. While the PR makes sure that these programs fail in proof_mode (as unsquashed dicts cannot be proven), they can still be ran without proof_mode, and therefore we should have tests that make sure that they can be serialized correctly.

**Comment by elielnfinic** [comment]
Can I work on this?

**Comment by pefontana** [comment]
done #1797
