### ISSUE TITLE
Cairo1-run InvocationError during sierra->casm compilation on programs with loops and recursion

### ISSUE THREAD

**Issue by Okm165** [lambdaclass/cairo-vm#1745]
**Bug Description:**
Encountering a compilation error during the `sierra` to `casm` compilation process in programs containing loops within the `cairo-vm` `cairo1-run` package. The error message indicates an `InvocationError` with the specific error being `UnknownVariableData`.
Full error message:
```
Error: Compilation(InvocationError { statement_idx: StatementIdx(23), error: UnknownVariableData })
```
---
**How to Reproduce:**
1. Set up a `scarb` project.
2. Paste the program.
```rust
fn main() -> felt252 {
    let mut i = 5;
    loop {
        if i == 0 {
            break;
        }
        i-=1;
    };
    i
}
```
3. Execute the following steps:
    - `scarb build`
    - `cargo run (path to sierra) --layout all_cairo`

It is important to note that if u `remove loop` from the above program the `cairo1-run succeeds` to run it

---
**Branch and Commit:**
- Branch: main
- Commit: 6c554e72be19a18d1ffe71e38f6d614c2a4d742f
- Scarb 2.6.3

**Comment by fmoletta** [comment]
Hello! Did you add the following to your Scarb.toml?
```
[cairo]
enable-gas = false
```

**Comment by Okm165** [comment]
@fmoletta Hi! It solves this issue! Thank u for quick response🚀🚀🚀
