### ISSUE TITLE
CairoVM runner is not checking `Relocatable` offset `i16` overflow during runtime

### ISSUE THREAD

**Issue by Okm165** [lambdaclass/cairo-vm#1848]
### Bug Description
When running programs with array inputs, the Cairo VM loads the input into a newly allocated memory segment. However, if the input exceeds `i16::MAX`, an issue occurs where the runner uses an offset of type `usize`, allowing it to pass the `checked_add` checks. The problem arises because the Cairo VM’s registers are of type `i16`, which cannot hold values beyond `i16::MAX`. This results in overflow issues when the input exceeds the `i16` limit.

### Expected Behavior
The VM should handle inputs in a way that ensures memory addresses and offsets are properly checked against the `i16` register limits, preventing overflows.

### Proposed Solution
- **Option 1:** Change the `Relocatable` type from `usize` to `i16`, ensuring that all memory addresses conform to the `i16` register limits.
- **Option 2:** Implement additional checks for `i16` overflow to ensure the VM handles out-of-bound memory addresses gracefully without breaking the program.

Reference code can be found [here](https://github.com/lambdaclass/cairo-vm/blob/3fb0344ce038b3a68cae897c403d1f561cfe8da7/vm/src/types/relocatable.rs#L21C1-L24C2).

The `i16` registers design is detailed in section 2.4 of the [Cairo Paper](https://www.cairo-lang.org/docs/).

### Additional Context
This overflow issue results from the disparity between the `usize` offset type in the runner and the `i16` registers in the VM. Ensuring consistency or adding appropriate checks would prevent this problem.

Let me know your thoughts on this approach.

**Cheers!**

**Comment by Okm165** [comment]
Sorry my bad copied link from wrong tab your is the one i intended to paste

**Comment by Okm165** [comment]
Ok i see you are right here let me try to reproduce the issue locally, will write soon.

**Comment by maciejka** [comment]
My guess is that Casm generated by the runner assumes that offset is always small and uses wrong addressing more.

**Comment by maciejka** [comment]
It seems like this bug is caused by overflows in the runner. This issue can be closed.

**Comment by Oppen** [comment]
Fair enough.
