### ISSUE TITLE
Cairo1-run security issue in proof mode

### ISSUE THREAD

**Issue by chudkowsky** [lambdaclass/cairo-vm#1886]
**Describe the bug**
First of all here is cairo program that i used:
```
fn main(input: Array<felt252>) -> Array<felt252> {
    array![1,2,3]
}
```
then i went into cairo1-run program
```
cd cairo1-run 
```

and run it with proof mode 
```
cargo run program.cairo --layout=small --air_public_input=public_input.json --air_private_input=private_input.json --trace_file=trace.bin --memory_file=memory.bin --proof_mode --args '[5 6 7]' 
```
after that when we inspect the public_input.json we can see
that in memory segments in output: 
```
"output": {
      "begin_addr": 114,
      "stop_ptr": 122
    },
```
as you can see first 4 elements are related to output 
and next 4 are input. 
```

{
  "address": 114,
  "value": "0x3", //output lenght 
  "page": 0
},
{
  "address": 115,
  "value": "0x1", //output
  "page": 0
},
{
  "address": 116,
  "value": "0x2", //output 
  "page": 0
},
{
  "address": 117,
  "value": "0x3", //output
  "page": 0
},
{
  "address": 118,
  "value": "0x3", //input length 
  "page": 0
},
{
  "address": 119,
  "value": "0x5", //input 
  "page": 0
},
{
  "address": 120,
  "value": "0x6", //input
  "page": 0
},
{
  "address": 121,
  "value": "0x7", //input
  "page": 0
}
```
so after proving with stone prover, proof contains input information. In cairo0 i didnt observe this bug
**To Reproduce**
clone the repo:
```https://github.com/lambdaclass/cairo-vm.git```
revision = `577f744`
program we will use:
```
fn main(input: Array<felt252>) -> Array<felt252> {
    array![1,2,3]
}
```

```
cd cairo1-run
cargo run program.cairo --layout=small --air_public_input=public_input.json --air_private_input=private_input.json --trace_file=trace.bin --memory_file=memory.bin --proof_mode --args '[5 6 7]' 
```

then if you inspect the public_input you can find explained bug.

**Expected behavior**

In proof mode, only the output of the program should be included in the air-public-input, while the input should remain private. This ensures the separation of input and output, which is crucial for security and scalability.

**Actual behavior** 
Both the input and the output are included in the air-public-input, leading to an unintended leakage of input data. This is not the expected behavior and could introduce vulnerabilities or inefficiencies in the proof generation process. After proof generation input remains in the proof.

**Impact**

#### Security Risk: 
Sensitive input data is inadvertently exposed in the proof, which could compromise the privacy of the 
execution.

#### Scalability:
Including input data in the proof increases the size of the proof, which could affect performance and scalability, especially for larger programs.

**Comment by gabrielbosio** [comment]
Hi! This is a design decision and the intended behavior as the [docs](https://github.com/lambdaclass/cairo-vm/blob/d2c056e4a89aec9901c176f056dbcc58dd4660e5/cairo1-run/README.md?plain=1#L72) mention it:

```
Adds extra instructions to the program in order to append the return and input values to the output builtin's segment. This is the default behaviour for proof_mode.
```

For more info, see the merged PR #1770 that implements this.
