### ISSUE TITLE
bug: `cairo1-run` expect a different number of arguments than what my main signature provides for when using `starknet::circuit`

### ISSUE THREAD

**Issue by tdelabro** [lambdaclass/cairo-vm#1888]
Hey,
I’m running the following program

```cairo
fn main(
    raw_inputs: Array<felt252>,
) -> Array<felt252> {
    let inputs: Inputs  = {
    let mut inputs_ref = raw_inputs.span();
     Serde::deserialize(ref inputs_ref).expect('bad program arguments')
    };

   // <do stuffs>
}
```
output:
```shell
cairo1-run target/release/$PROGRAM_NAME.sierra.json \
  --args "[650157136941007917207724121471813482783483983289688285320161307177215463403 1655569645808460179723299787189716707852181277595105475126938070374837146371]"  \
  --layout=$LAYOUT
  ```
  all good

  Now I edit my program:
```cairo
fn main(
    raw_inputs: Array<felt252>,
) -> Array<felt252> {
    let in1 = CircuitElement::<CircuitInput<0>> {};
    let in2 = CircuitElement::<CircuitInput<1>> {};
    let add = circuit_add(in1, in2);
    let inv = circuit_inverse(add);
    let sub = circuit_sub(inv, in2);
    let mul = circuit_mul(inv, sub);

    let modulus = TryInto::<_, CircuitModulus>::try_into([7, 0, 0, 0]).unwrap();
    let outputs = (mul, add, inv)
        .new_inputs()
        .next([3, 0, 0, 0])
        .next([6, 0, 0, 0])
        .done()
        .eval(modulus)
        .unwrap();

    assert!(outputs.get_output(add) == u384 { limb0: 2, limb1: 0, limb2: 0, limb3: 0 });
    assert!(outputs.get_output(inv) == u384 { limb0: 4, limb1: 0, limb2: 0, limb3: 0 });
    assert!(outputs.get_output(sub) == u384 { limb0: 5, limb1: 0, limb2: 0, limb3: 0 });
    assert!(outputs.get_output(mul) == u384 { limb0: 6, limb1: 0, limb2: 0, limb3: 0 });

    let inputs: Inputs  = {
    let mut inputs_ref = raw_inputs.span();
     Serde::deserialize(ref inputs_ref).expect('bad program arguments')
    };

   // Do things
}
```

Let’s run:
```shell
cairo1-run target/release/$PROGRAM_NAME.sierra.json \
  --args "[650157136941007917207724121471813482783483983289688285320161307177215463403 1655569645808460179723299787189716707852181277595105475126938070374837146371]"  \
  --layout=$LAYOUT


Error: ArgumentsSizeMismatch { expected: 5, actual: 2 }
```
Oh oh
Adding this code makes cairo1-run expect a different number of arguments now.
This will allow the execution to happen.
 `"1 2 3 [650157136941007917207724121471813482783483983289688285320161307177215463403 1655569645808460179723299787189716707852181277595105475126938070374837146371]" `

**Comment by FrancoGiachetta** [comment]
Hi @tdelabro! 
Programs which involve using circuits requiere the `mod_builtin` feature to be active. This is done so that `AddMod` and `MulMod` builtins are taken into account. I would suggest to compile the binary again, making sure that this feature is active. Since the builtins are implicit arguments, this might explain why the program is receiving only 2 arguments. It also explains why the `add_mod` segment is missing when executing the program with the stone prover.

Let me know if this solves the issue.

**Comment by tdelabro** [comment]
@FrancoGiachetta Thanks

This is not part of the latest release you published, the one I was working with: https://github.com/lambdaclass/cairo-vm/releases

And, obviously, it is not mentioned in the readme of the crate: https://github.com/lambdaclass/cairo-vm/tree/main/cairo1-run.
You need to add a section about it explaining when and why to use it

**Comment by FrancoGiachetta** [comment]
You are totally right. I'll add it to the readme, thanks for pointing that out.

**Comment by FrancoGiachetta** [comment]
I'll close the issue as it has been solved. Also a PR has been create to document better how to use circuits in cairo 1. If there's anything else pin us!
