### ISSUE TITLE
Improve the experience of building this repo

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/cairo-vm#713]
**Problem**
There are several steps in the building of the cairo-rs repository that fail. Navigating the errors is cumbersome, especially if you're building it for the first time and have no context of what's causing the error. Devs that work daily in this repo already know the hacks but they're not documented. 

**Solution 1: Devops**
Use some devops magic to make the build easier by preventing these issues to come up. 

**Solution 2: Document**
Work around any remaining issues by improving documentation:
- Describe the step by step process of building this repo.
- Create a FAQ section for known issues.
- Test by doing a clean install in as many relevant operating systems/processors as we can.

**Comment by MegaRedHand** [comment]
Tackled in #1298
